# Markdownlint is checker and lint library in NodeJS for Markdown/CommonMark.
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# 关于 markdownlint-cli2 => https://dlaa.me/blog/post/markdownlintcli2
# 全局安装 $ npm install --global markdownlint-cli2
# 检测命令 $ markdownlint-cli2 --no-globs README.md

# Enable default value for all rules
default: true

# Path to configuration file to extend
extends: null

# Heading levels should only increment by one level at a time
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md001.md
MD001: true

# Heading Style
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md003.md
MD003:
  style: "consistent"

# Unordered list style
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md004.md
MD004:
  style: "sublist"

# Inconsistent indentation for list items at the same level
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md005.md
MD005: true

# Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2
  # Whether indent the first level of the list item
  start_indented: false
  # Spaces for first level indent when start_indented true
  start_indent: 2

# Trailing spaces
MD009:
  # Include unnecessary breaks
  strict: false
  # Spaces for line break
  br_spaces: 2
  # Allow spaces for empty lines in list items
  list_item_empty_lines: false

# Hard tabs
MD010:
  # Number of spaces for each hard tab
  spaces_per_tab: 2
  # Include code blocks
  code_blocks: true
  # Fenced code languages to ignore
  ignore_code_languages: []

# Reversed link syntax
MD011: true

# Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 1

# Line length of characters
MD013:
  # Number of characters
  line_length: 150
  # Number of characters for headings
  heading_line_length: 150
  # Number of characters for code blocks
  code_block_line_length: 150
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# Dollar signs used before commands without showing output
MD014: true

# No space after hash on atx style heading
MD018: true

# Multiple spaces after hash on atx style heading
MD019: true

# No space inside hashes on closed atx style heading
MD020: true

# Multiple spaces inside hashes on closed atx style heading
MD021: true

# Headings should be surrounded by blank lines
MD022:
  # Blank lines above heading
  lines_above: 1
  # Blank lines below heading
  lines_below: 1

# Headings must start at the beginning of the line
MD023: true

# Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: false

# Multiple top-level headings in the same document
MD025:
  # Heading level
  level: 1
  # RegExp for matching title in front matter
  front_matter_title: "^\\s*title\\s*[:=]"

# Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:!。，；：！"

# Multiple spaces after blockquote symbol
MD027: true

# Blank line inside blockquote
MD028: true

# Ordered list item prefix
MD029:
  # List style
  style: "one_or_ordered"

# Spaces after list markers
MD030:
  # Spaces for single-line unordered list items
  ul_single: 1
  # Spaces for single-line ordered list items
  ol_single: 1
  # Spaces for multi-line unordered list items
  ul_multi: 1
  # Spaces for multi-line ordered list items
  ol_multi: 1

# Fenced code blocks should be surrounded by blank lines
MD031:
  # Include list items
  list_items: true

# Lists should be surrounded by blank lines
MD032: true

# Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [
    h1, h2, h3, h4, h5, h6, div, img, br, a, strong
  ]

# Bare URL used
MD034: true

# Horizontal rule style
MD035:
  # Horizontal rule style
  style: "consistent"

# Emphasis used instead of a heading
MD036:
  # Punctuation characters
  punctuation: ".,;:!?。，；：！？"

# Spaces inside emphasis markers
MD037: true

# Spaces inside code span elements
MD038: true

# Spaces inside link text
MD039: true

# Fenced code blocks should have a language specified
MD040:
  # List of languages
  allowed_languages: []
  # Require language only
  language_only: false

# First line in a file should be a top-level heading
MD041: false

# No empty links
MD042: true

# Required heading structure
MD043:
  # List of headings
  headings: [ '*' ]
  # Match case of headings
  match_case: false

# Proper names should have the correct capitalization
MD044:
  # List of proper names
  names: []
  # Include code blocks
  code_blocks: true
  # Include HTML elements
  html_elements: true

# Images should have alternate text (alt text)
MD045: true

# Code block style
MD046:
  # Block style
  style: "consistent"

# Files should end with a single newline character
MD047: true

# Code fence style
MD048:
  # Code fence style
  style: "consistent"

# Emphasis style
MD049:
  # Emphasis style
  style: "consistent"

# Strong style
MD050:
  # Strong style
  style: "consistent"

# Link fragments should be valid
MD051: true

# Reference links and images should use a label that is defined
MD052:
  # Include shortcut syntax
  shortcut_syntax: false

# Link and image reference definitions should be needed
MD053:
  # Ignored definitions
  ignored_definitions:
    - "//"

# Link and image style
MD054:
  # Allow autolinks
  autolink: true
  # Allow inline links and images
  inline: true
  # Allow full reference links and images
  full: true
  # Allow collapsed reference links and images
  collapsed: true
  # Allow shortcut reference links and images
  shortcut: true
  # Allow URLs as inline links
  url_inline: true

# Table pipe style
MD055:
  # Table pipe style
  style: "consistent"

# Table column count
MD056: true
