# https://docs.github.com/articles/workflow-syntax-for-github-actions
name: "[TODO] CI the pull request changed files"

on:
  pull_request:
    branches:
      - trunk

jobs:
  ci-pull-request:
    if: github.repository == 'xwlc/mini-repo'
    runs-on: ubuntu-latest
    # Set permissions to `read-all`, preventing workflow
    # from any accidental write access to the repository.
    permissions: read-all
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      # This is the directory where the built files will be placed.
      BUILD_OUT_ROOT: build
    steps:
      - uses: actions/checkout@v4
      # https://docs.github.com/rest/commits/commits#compare-two-commits
      - name: Get the list of changed files by the pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API to get the list of changed files
          PR_DIFF_FILES=$(gh api repos/{owner}/{repo}/compare/${{ env.BASE_SHA }}...${{ env.HEAD_SHA }} \
            --jq '.files | .[] | select(.status|IN("added", "modified", "renamed", "copied", "changed")) | .filename')

          # Filter out files that are not markdown files
          PR_CHANGED_MD=$(echo "${PR_DIFF_FILES}" | egrep -i "^files/.*\.(md)$" | xargs)
          echo "PR_CHANGED_MD=${PR_CHANGED_MD}" >> ${GITHUB_ENV}

      - name: What ...
        if: ${{ env.PR_CHANGED_MD }}
        run: echo -e "PR Changed *.md List\n${{ env.PR_CHANGED_MD }}"
