# https://docs.github.com/articles/workflow-syntax-for-github-actions
name: "Lint all *.md files by markdownlint"

# NOTE 当且仅当 trunk 分支 push 或 PR 事件: 修改(paths)指定文件时触发

on:
  push:
    branches:
      - trunk
    paths:
      - "**.md"
      - util/mdlint.sh
      - .markdownlint.yaml
      - .github/workflows/lint-markdown.yml
  pull_request:
    branches:
      - trunk
    paths:
      - "**.md"
      - util/mdlint.sh
      - .markdownlint.yaml
      - .github/workflows/lint-markdown.yml

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install --global markdownlint-cli2
      - run: util/mdlint.sh
